name: Check the source code
on: push
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: yarn format:prettier
      - name: Lint
        run: yarn format:eslint 
