name: Check the source code
on:
  pull_request:
    branches:
      - master
      - develop
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: yarn format:prettier
      - name: Lint
        run: yarn format:eslint

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_USERNAME: Github Actions
          SLACK_CHANNEL: alquimista_hp_pr
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
          SLACK_MESSAGE: 'Post Content :rocket:'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_USERNAME: Github Actions
          SLACK_CHANNEL: alquimista_hp_pr
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Post Content :rocket:'
